// import dayjs from 'dayjs'

// describe('Study Rights', () => {
//   before(() => {
//     cy.resetTestDatabase()
//   })

//   beforeEach(() => {
//     cy.intercept('POST', '/etudes/*/cadrage/ajouter').as('create')
//     cy.intercept('POST', '/etudes/*/cadrage/ajouter-contributeur').as('createContributor')
//     cy.intercept('POST', '/etudes/*/cadrage/modifier-contributeur/*').as('editContributor')
//     cy.intercept('POST', '/etudes/*/cadrage').as('update')
//   })

//   it('should show not in your orga for CR only when necessary', () => {
//     cy.login('bc-cr-admin-1@yopmail.com', 'password-1')
//     cy.getByTestId('organization').first().click()
//     cy.getByTestId('new-study').click()
//     cy.getByTestId('organization-sites-checkbox').first().should('be.visible').find('input').check({ force: true })
//     cy.getByTestId('new-study-organization-button').should('not.be.disabled').click()
//     cy.getByTestId('new-study-name').scrollIntoView()
//     cy.getByTestId('new-study-name').should('be.visible')
//     cy.getByTestId('new-study-name').type('Study with rights')
//     cy.getByTestId('new-study-level').click()
//     cy.get('[data-value="Standard"]').click()
//     cy.getByTestId('new-validator-name').type('bc-cr-gestionnaire-1@yopmail.com')
//     cy.get('[data-option-index="0"]').click()
//     cy.getByTestId('new-study-endDate').within(() => {
//       cy.get('span').first().type(dayjs().add(1, 'y').format('DD/MM/YYYY'))
//     })
//     cy.getByTestId('new-study-create-button').click()
//     cy.getByTestId('study-cadrage-link').click()
//     cy.getByTestId('study-rights-table-row').contains('bc-cr-gestionnaire-1@yopmail.comValidateur')
//     // External user
//     cy.getByTestId('study-rights-change-button').click()
//     cy.getByTestId('study-rights-email').should('be.visible')
//     cy.getByTestId('study-rights-email').type('bc-external@yopmail.com')
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Reader"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.get('#new-study-right-modal-title').should('be.visible')
//     cy.get('#new-study-right-other-organization-warning').should('be.visible')
//     cy.get('#new-study-right-other-organization-warning')
//       .invoke('text')
//       .should('include', 'Elle ne fait pas partie de votre organisation')
//     cy.get('#new-study-right-other-organization-warning')
//       .invoke('text')
//       .should('not.include', 'Si elle ne réunit pas les conditions nécessaires')
//     cy.getByTestId('new-study-right-modal-decline').click()
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Editor"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.get('#new-study-right-modal-title').should('be.visible')
//     cy.get('#new-study-right-other-organization-warning').should('be.visible')
//     cy.getByTestId('new-study-right-modal-accept').click()
//     cy.wait('@create')
//     cy.getByTestId('study-rights-table-row').contains('bc-external@yopmail.comLecteur')
//     // Internal user
//     cy.getByTestId('study-rights-change-button').click()
//     cy.getByTestId('study-rights-email').should('be.visible')
//     cy.getByTestId('study-rights-email').type('bc-cr-default-1@yopmail.com')
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Reader"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.get('#new-study-right-modal-title').should('not.exist')
//     cy.wait('@create')
//     cy.getByTestId('study-rights-table-row').contains('bc-cr-default-1@yopmail.comLecteur')
//   })

//   it('should set user and manage role according to given rights', () => {
//     cy.login('bc-admin-1@yopmail.com', 'password-1')
//     cy.getByTestId('new-study').click()
//     cy.getByTestId('organization-sites-checkbox').first().should('be.visible').find('input').check({ force: true })
//     cy.getByTestId('new-study-organization-button').should('not.be.disabled').click()
//     cy.getByTestId('new-study-name').scrollIntoView()
//     cy.getByTestId('new-study-name').should('be.visible')
//     cy.getByTestId('new-study-name').type('Study with rights')
//     cy.getByTestId('new-study-level').click()
//     cy.get('[data-value="Standard"]').click()
//     cy.getByTestId('new-validator-name').type('bc-GEstionnaire-1@yopmail.com')
//     cy.get('[data-option-index="0"]').click()
//     cy.getByTestId('new-study-endDate').within(() => {
//       cy.get('span').first().type(dayjs().add(1, 'y').format('DD/MM/YYYY'))
//     })
//     cy.getByTestId('new-study-create-button').click()
//     cy.getByTestId('study-cadrage-link').click()
//     cy.getByTestId('study-rights-table-row').contains('bc-gestionnaire-1@yopmail.comValidateur')
//     // External user
//     cy.getByTestId('study-rights-change-button').click()
//     cy.getByTestId('study-rights-email').should('be.visible')
//     cy.getByTestId('study-rights-email').type('bc-external@yopmail.com')
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Reader"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.get('#new-study-right-modal-title').should('be.visible')
//     cy.get('#new-study-right-other-organization-warning').should('be.visible')
//     cy.get('#new-study-right-other-organization-warning')
//       .invoke('text')
//       .should('include', 'Elle ne fait pas partie de votre organisation')
//     cy.get('#new-study-right-other-organization-warning')
//       .invoke('text')
//       .should('not.include', 'Si elle ne réunit pas les conditions nécessaires')
//     cy.getByTestId('new-study-right-modal-decline').click()
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Editor"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.get('#new-study-right-modal-title').should('be.visible')
//     cy.get('#new-study-right-other-organization-warning').should('be.visible')
//     cy.getByTestId('new-study-right-modal-accept').click()
//     cy.wait('@create')
//     cy.getByTestId('study-rights-table-row').contains('bc-external@yopmail.comLecteur')
//     // Existing user outside of organization without rights
//     cy.getByTestId('study-rights-change-button').click()
//     cy.getByTestId('study-rights-email').type('bc-collaborator-2@yopmail.com')
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Reader"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.get('#new-study-right-other-organization-warning').should('be.visible')
//     cy.getByTestId('new-study-right-modal-decline').click()
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Editor"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.get('#new-study-right-other-organization-warning').should('be.visible')
//     cy.getByTestId('new-study-right-modal-accept').click()
//     cy.wait('@create')
//     cy.getByTestId('study-rights-table-row').eq(1).contains('bc-collaborator-2@yopmail.comLecteur')
//     // Existing user outside of organization with rights
//     cy.getByTestId('study-rights-change-button').click()
//     cy.getByTestId('study-rights-email').type('bc-collaborator-0@yopmail.com')
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Editor"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.getByTestId('new-study-right-modal-accept').click()
//     cy.wait('@create')
//     cy.getByTestId('study-rights-table-row').eq(1).contains('bc-collaborator-0@yopmail.comÉditeur')
//     cy.getByTestId('study-rights-change-button').click()
//     cy.getByTestId('study-rights-email').type('bc-admin-0@yopmail.com')
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Editor"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.getByTestId('new-study-right-modal-accept').click()
//     cy.wait('@create')
//     cy.getByTestId('study-rights-table-row').eq(0).contains('bc-admin-0@yopmail.comÉditeur')
//     // Organization's user without rights
//     cy.getByTestId('study-rights-change-button').click()
//     cy.getByTestId('study-rights-email').click()
//     cy.contains('[data-option-index]', 'bc-collaborator-1@yopmail.com').click()
//     cy.getByTestId('study-rights-role').within(() => {
//       cy.get('input').should('have.value', '')
//       cy.get('input').should('not.be.disabled')
//     })
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Validator"]').click()
//     cy.getByTestId('study-rights-email').click()
//     cy.contains('[data-option-index]', 'untrained@yopmail.com').click()
//     cy.getByTestId('study-rights-role').within(() => {
//       cy.get('input').should('have.value', 'Reader')
//       cy.get('input').should('be.disabled')
//     })
//     cy.getByTestId('study-rights-create-button').click()
//     cy.wait('@create')
//     cy.getByTestId('study-rights-table-row').eq(6).contains('untrained@yopmail.comLecteur')
//     // Organization's user with rights
//     cy.getByTestId('study-rights-change-button').click()
//     cy.getByTestId('study-rights-email').click()
//     cy.contains('[data-option-index]', 'bc-collaborator-1@yopmail.com').click()
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Validator"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.wait('@create')
//     cy.getByTestId('study-rights-table-row').eq(3).contains('bc-collaborator-1@yopmail.comValidateur')
//     cy.getByTestId('study-rights-table-row')
//       .eq(3)
//       .within(() => cy.get('input').should('not.be.disabled'))
//     // Rights management
//     // cannot edit its own rights
//     cy.getByTestId('study-rights-table-row').eq(1).contains('bc-admin-1@yopmail.comValidateur')
//     cy.getByTestId('study-rights-table-row')
//       .eq(1)
//       .within(() => {
//         cy.get('input').should('be.disabled')
//       })
//     // cannot edit external or untrained user's rights
//     cy.getByTestId('study-rights-table-row').eq(4).contains('bc-collaborator-2@yopmail.comLecteur')
//     cy.getByTestId('study-rights-table-row')
//       .eq(4)
//       .within(() => cy.get('input').should('be.disabled'))
//     cy.getByTestId('study-rights-table-row').eq(5).contains('bc-external@yopmail.comLecteur')
//     cy.getByTestId('study-rights-table-row')
//       .eq(5)
//       .within(() => cy.get('input').should('be.disabled'))
//     cy.getByTestId('study-rights-table-row').eq(7).contains('untrained@yopmail.comLecteur')
//     cy.getByTestId('study-rights-table-row')
//       .eq(7)
//       .within(() => cy.get('input').should('be.disabled'))
//     // Validators can edit other people's rights
//     cy.getByTestId('study-rights-table-row').eq(3).contains('bc-collaborator-1@yopmail.comValidateur')
//     cy.getByTestId('study-rights-table-row')
//       .eq(3)
//       .within(() => {
//         cy.get('input').should('not.be.disabled')
//         cy.get('.MuiSelect-select').click()
//       })
//     cy.get('[data-value="Editor"]').click()
//     cy.wait('@update')
//     cy.getByTestId('study-rights-table-row').eq(3).contains('bc-collaborator-1@yopmail.comÉditeur')
//     // Editors cannot edit validator's rights
//     cy.url().then((link) => {
//       cy.logout()
//       cy.login('bc-collaborator-0@yopmail.com', 'password-0')
//       cy.visit(link)
//     })
//     cy.getByTestId('study-rights-change-button').should('exist')
//     cy.getByTestId('select-study-role').should('exist')
//     cy.getByTestId('study-rights-table-row').eq(1).contains('bc-admin-1@yopmail.comValidateur')
//     cy.getByTestId('study-rights-table-row')
//       .eq(1)
//       .within(() => cy.get('input').should('be.disabled'))
//     // Editors can't select validator's rights
//     cy.getByTestId('study-rights-table-row').eq(0).contains('bc-admin-0@yopmail.comÉditeur')
//     cy.getByTestId('study-rights-table-row')
//       .eq(0)
//       .within(() => {
//         cy.get('input').should('not.be.disabled')
//         cy.get('.MuiSelect-select').click()
//       })
//     cy.get('[data-value="Reader"]').should('exist')
//     cy.get('[data-value="Editor"]').should('exist')
//     cy.get('[data-value="Validator"]').should('not.exist')
//     cy.get('[data-value="Reader"]').click()
//     // Readers can't update rights
//     cy.go('back')
//     cy.url().then((link) => {
//       cy.logout()
//       cy.login()
//       cy.visit(link)
//     })
//     cy.getByTestId('study-rights-change-button').should('not.exist')
//     cy.getByTestId('select-study-role').should('not.exist')
//   })

//   it('study members deletion rights', () => {
//     cy.login('bc-admin-1@yopmail.com', 'password-1')
//     cy.getByTestId('new-study').click()
//     cy.getByTestId('organization-sites-checkbox').first().should('be.visible').find('input').check({ force: true })
//     cy.getByTestId('new-study-organization-button').should('not.be.disabled').click()
//     cy.getByTestId('new-study-name').scrollIntoView()
//     cy.getByTestId('new-study-name').type('Study with deletion rights')
//     cy.getByTestId('new-study-level').click()
//     cy.get('[data-value="Standard"]').click()
//     cy.getByTestId('new-validator-name').type('bc-collaborator-1@yopmail.com')
//     cy.get('[data-option-index="0"]').click()
//     cy.getByTestId('new-study-endDate').within(() => {
//       cy.get('span').first().type(dayjs().add(1, 'y').format('DD/MM/YYYY'))
//     })
//     cy.getByTestId('new-study-create-button').click()
//     cy.getByTestId('study-cadrage-link').click()
//     cy.getByTestId('study-rights-change-button').click()
//     cy.getByTestId('study-rights-email').click()
//     cy.contains('[data-option-index]', 'bc-gestionnaire-1@yopmail.com').click()
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Reader"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.wait('@create')
//     cy.getByTestId('study-rights-table-row').should('have.length', 3)
//     cy.getByTestId('study-rights-table-row').eq(1).scrollIntoView()
//     cy.getByTestId('study-rights-table-row')
//       .eq(0)
//       .within(() => {
//         cy.get('td').first().should('have.text', 'bc-admin-1@yopmail.com')
//         cy.getByTestId('delete-study-member-button').should('not.exist')
//       })
//     cy.getByTestId('study-rights-table-row').eq(1).scrollIntoView()
//     cy.getByTestId('study-rights-table-row')
//       .eq(1)
//       .within(() => {
//         cy.get('td').first().should('have.text', 'bc-collaborator-1@yopmail.com')
//         cy.getByTestId('delete-study-member-button').should('be.visible')
//         cy.getByTestId('delete-study-member-button').click()
//       })
//     cy.get('#study-member-deletion-modal-description').should('be.visible')
//     cy.get('#study-member-deletion-modal-description').invoke('text').should('contain', 'bc-collaborator-1@yopmail.com')
//     cy.getByTestId('study-member-cancel-deletion').click()
//     cy.getByTestId('study-member-deletion-modal-description').should('not.exist')
//     cy.getByTestId('study-rights-table-row')
//       .eq(1)
//       .within(() => {
//         cy.getByTestId('delete-study-member-button').click()
//       })
//     cy.get('#study-member-deletion-modal-description').should('be.visible')
//     cy.getByTestId('study-member-confirm-deletion').click()
//     cy.getByTestId('study-rights-table-row').should('have.length', 2)
//     cy.getByTestId('study-rights-table-row')
//       .eq(1)
//       .within(() => {
//         cy.get('td').first().should('have.text', 'bc-gestionnaire-1@yopmail.com')
//       })
//     cy.url().then((savedUrl) => {
//       cy.logout()
//       cy.login('bc-gestionnaire-1@yopmail.com', 'password-1')
//       cy.visit(savedUrl)
//       cy.getByTestId('delete-study-member-button').should('not.exist')
//     })
//   })

//   it('study contributors deletion rights', () => {
//     cy.login('bc-admin-1@yopmail.com', 'password-1')
//     cy.getByTestId('new-study').click()
//     cy.getByTestId('organization-sites-checkbox').first().should('be.visible').find('input').check({ force: true })
//     cy.getByTestId('new-study-organization-button').should('not.be.disabled').click()
//     cy.getByTestId('new-study-name').scrollIntoView()
//     cy.getByTestId('new-study-name').type('Study with contributor deletion rights')
//     cy.getByTestId('new-study-level').click()
//     cy.get('[data-value="Standard"]').click()
//     cy.getByTestId('new-validator-name').type('bc-admin-1@yopmail.com')
//     cy.get('[data-option-index="0"]').click()
//     cy.getByTestId('new-study-endDate').within(() => {
//       cy.get('span').first().type(dayjs().add(1, 'y').format('DD/MM/YYYY'))
//     })
//     cy.getByTestId('new-study-create-button').click()
//     cy.getByTestId('study-cadrage-link').click()
//     cy.getByTestId('study-rights-change-button').click()
//     cy.getByTestId('study-rights-email').click()
//     cy.contains('[data-option-index]', 'bc-default-1@yopmail.com').click()
//     cy.getByTestId('study-rights-role').click()
//     cy.get('[data-value="Reader"]').click()
//     cy.getByTestId('study-rights-create-button').click()
//     cy.wait('@create')
//     cy.getByTestId('study-rights-add-contributor').scrollIntoView()
//     cy.getByTestId('study-rights-add-contributor').click()
//     cy.getByTestId('study-contributor-email').type('contributor-to-delete@yopmail.com')
//     cy.get('#mui-component-select-post').click()
//     cy.get('[data-value="AutresEmissionsNonEnergetiques"]').click()
//     cy.getByTestId('emission-factor-subPost').click()
//     cy.get('[data-value="Agriculture"]').click()
//     cy.get('body').click(0, 0)
//     cy.getByTestId('study-contributor-create-button').click()
//     cy.getByTestId('new-study-right-modal-accept').click()

//     cy.wait('@createContributor')
//     cy.getByTestId('study-rights-add-contributor').scrollIntoView()
//     cy.getByTestId('study-rights-add-contributor').click()
//     cy.getByTestId('study-contributor-email').type('contributor-to-remain@yopmail.com')
//     cy.get('#mui-component-select-post').click()
//     cy.get('[data-value="AutresEmissionsNonEnergetiques"]').click()
//     cy.getByTestId('emission-factor-subPost').click()
//     cy.get('[data-value="Agriculture"]').click()
//     cy.get('body').click(0, 0)
//     cy.getByTestId('study-contributor-create-button').click()
//     cy.getByTestId('new-study-right-modal-accept').click()

//     cy.wait('@createContributor')
//     cy.getByTestId('study-contributors-table-row').first().scrollIntoView()
//     cy.getByTestId('study-contributors-table-row').should('have.length', 2)
//     cy.getByTestId('study-contributors-table-row')
//       .first()
//       .invoke('text')
//       .should('include', 'contributor-to-delete@yopmail.com')
//     cy.getByTestId('delete-study-contributor-button').first().click()
//     cy.get('#study-contributor-deletion-modal-description').should('be.visible')
//     cy.get('#study-contributor-deletion-modal-description')
//       .invoke('text')
//       .should('contain', 'contributor-to-delete@yopmail.com')
//     cy.getByTestId('study-contributor-cancel-deletion').click()
//     cy.getByTestId('study-contributor-deletion-modal-description').should('not.exist')
//     cy.getByTestId('delete-study-contributor-button').first().click()
//     cy.get('#study-contributor-deletion-modal-description').should('be.visible')
//     cy.getByTestId('study-contributor-confirm-deletion').click()
//     cy.getByTestId('study-contributors-table-row').should('have.length', 1)
//     cy.getByTestId('study-contributors-table-row')
//       .first()
//       .invoke('text')
//       .should('include', 'contributor-to-remain@yopmail.com')
//     cy.url().then((savedUrl) => {
//       cy.logout()
//       cy.login('bc-default-1@yopmail.com', 'password-1')
//       cy.visit(savedUrl)
//       cy.getByTestId('study-contributors-table-row').first().scrollIntoView()
//       cy.getByTestId('delete-study-contributor-button').should('not.exist')
//     })
//   })

//   it('study contributors edition rights', () => {
//     cy.login('bc-admin-1@yopmail.com', 'password-1')
//     cy.getByTestId('new-study').click()
//     cy.getByTestId('organization-sites-checkbox').first().should('be.visible').find('input').check({ force: true })
//     cy.getByTestId('new-study-organization-button').should('not.be.disabled').click()
//     cy.getByTestId('new-study-name').scrollIntoView()
//     cy.getByTestId('new-study-name').type('Study with contributor deletion rights')
//     cy.getByTestId('new-study-level').click()
//     cy.get('[data-value="Standard"]').click()
//     cy.getByTestId('new-validator-name').type('bc-admin-1@yopmail.com')
//     cy.get('[data-option-index="0"]').click()
//     cy.getByTestId('new-study-endDate').within(() => {
//       cy.get('span').first().type(dayjs().add(1, 'y').format('DD/MM/YYYY'))
//     })
//     cy.getByTestId('new-study-create-button').click()
//     cy.getByTestId('study-cadrage-link').click()
//     cy.getByTestId('study-rights-add-contributor').scrollIntoView()
//     cy.getByTestId('study-rights-add-contributor').click()
//     cy.getByTestId('study-contributor-email').type('contributor-to-edit@yopmail.com')
//     cy.get('#mui-component-select-post').click()
//     cy.get('[data-value="AutresEmissionsNonEnergetiques"]').click()
//     cy.getByTestId('emission-factor-subPost').click()
//     cy.get('[data-value="Agriculture"]').click()
//     cy.get('body').click(0, 0)
//     cy.getByTestId('study-contributor-create-button').click()
//     cy.getByTestId('new-study-right-modal-accept').click()

//     cy.wait('@createContributor')

//     cy.getByTestId('study-contributors-table-row').first().scrollIntoView()
//     cy.getByTestId('edit-study-contributor-button').first().click()

//     cy.get('#mui-component-select-post').click()
//     cy.get('[data-value="IntrantsBiensEtMatieres"]').click()
//     cy.getByTestId('emission-factor-subPost').click()
//     cy.get('[data-value="MetauxPlastiquesEtVerre"]').click()
//     cy.get('body').click(0, 0)
//     cy.getByTestId('study-contributor-create-button').click()
//     cy.wait('@editContributor')
//   })

//   it('admin user default role is validator', () => {
//     cy.login('bc-admin-0@yopmail.com', 'password-0')
//     cy.getByTestId('new-study').click()
//     cy.getByTestId('organization-sites-checkbox').first().should('be.visible').find('input').check({ force: true })
//     cy.getByTestId('new-study-organization-button').should('not.be.disabled').click()
//     cy.getByTestId('new-study-name').scrollIntoView()
//     cy.getByTestId('new-study-name').should('be.visible').type('Study from admin')
//     cy.getByTestId('new-validator-name').type('bc-collaborator-0@yopmail.com')
//     cy.get('[data-option-index="0"]').click()
//     cy.getByTestId('new-study-endDate').within(() => {
//       cy.get('span').first().type(dayjs().add(1, 'y').format('DD/MM/YYYY'))
//     })
//     cy.getByTestId('new-study-level').click()
//     cy.get('[data-value="Initial"]').click()
//     cy.getByTestId('new-study-create-button').click()
//     cy.getByTestId('study-cadrage-link').click()
//     cy.getByTestId('study-rights-table-row').eq(1).contains('bc-collaborator-0@yopmail.comValidateur')
//     cy.getByTestId('study-rights-table-row').eq(0).contains('bc-admin-0@yopmail.comValidateur')
//   })

//   it('non admin user default role is editor', () => {
//     cy.login()
//     cy.getByTestId('new-study').click()
//     cy.getByTestId('organization-sites-checkbox').first().should('be.visible').find('input').check({ force: true })
//     cy.getByTestId('new-study-organization-button').should('not.be.disabled').click()
//     cy.getByTestId('new-study-name').scrollIntoView()
//     cy.getByTestId('new-study-name').should('be.visible').type('Study from non admin')
//     cy.getByTestId('new-validator-name').type('bc-gestionnaire-0@yopmail.com')
//     cy.get('[data-option-index="0"]').click()
//     cy.getByTestId('new-study-endDate').within(() => {
//       cy.get('span').first().type(dayjs().add(1, 'y').format('DD/MM/YYYY'))
//     })
//     cy.getByTestId('new-study-level').click()
//     cy.get('[data-value="Initial"]').click()
//     cy.getByTestId('new-study-create-button').click()
//     cy.getByTestId('study-cadrage-link').click()
//     cy.getByTestId('study-rights-table-row').eq(1).contains('bc-gestionnaire-0@yopmail.comValidateur')
//     cy.getByTestId('study-rights-table-row').eq(0).contains('bc-collaborator-0@yopmail.comÉditeur')
//   })
// })
