export enum EngagementActionTargets {
  TEAM_PROJECT = 'TEAM_PROJECT',
  DIRECTION = 'DIRECTION',
  OTHER_INTERNAL_COLLABORATORS = 'OTHER_INTERNAL_COLLABORATORS',
  FURNISHERS = 'FURNISHERS',
  CLIENTS = 'CLIENTS',
  PARTNERS = 'PARTNERS',
  OTHERS_EXTERNAL = 'OTHERS_EXTERNAL',
}

export enum EngagementActionSteps {
  AT_LAUNCH_OF_APPROACH = 'AT_LAUNCH_OF_APPROACH',
  AT_LAUNCH_OF_DATA_COLLECTION = 'AT_LAUNCH_OF_DATA_COLLECTION',
  FOR_GES_PROFILE_CONSTRUCTION = 'FOR_GES_PROFILE_CONSTRUCTION',
  FOR_TRANSITION_PLAN_CONSTRUCTION = 'FOR_TRANSITION_PLAN_CONSTRUCTION',
  IN_SUMMARY_OF_APPROACH = 'IN_SUMMARY_OF_APPROACH',
  FOR_APPROACH_EVALUATION = 'FOR_APPROACH_EVALUATION',
}
