-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "Unit" ADD VALUE 'CAR';
ALTER TYPE "Unit" ADD VALUE 'KG_GAZOLINE_PER_KM';
ALTER TYPE "Unit" ADD VALUE 'KG_PER_KM';
ALTER TYPE "Unit" ADD VALUE 'KG_PER_CAR_KM';
ALTER TYPE "Unit" ADD VALUE 'KG_PER_KM_CAR';
ALTER TYPE "Unit" ADD VALUE 'KG_PER_KM_PASSENGER';
ALTER TYPE "Unit" ADD VALUE 'KG_PER_PASSENGER_KM';
ALTER TYPE "Unit" ADD VALUE 'KG_PER_TON_KM';
ALTER TYPE "Unit" ADD VALUE 'KM_PER_JOURNEY';
ALTER TYPE "Unit" ADD VALUE 'KNOTS';
ALTER TYPE "Unit" ADD VALUE 'KWH_ELEC_TON';
ALTER TYPE "Unit" ADD VALUE 'KWH_PER_KM';
ALTER TYPE "Unit" ADD VALUE 'KWH_PER_PASSENGER_KM';
ALTER TYPE "Unit" ADD VALUE 'KWH_THERM_TON';
ALTER TYPE "Unit" ADD VALUE 'KWH_PCI_TON';
ALTER TYPE "Unit" ADD VALUE 'KWH_PER_TON_KM';
ALTER TYPE "Unit" ADD VALUE 'LITER_PER_ERRAND_KM';
ALTER TYPE "Unit" ADD VALUE 'LITER_PER_KM';
ALTER TYPE "Unit" ADD VALUE 'LITER_PER_M3_KM';
ALTER TYPE "Unit" ADD VALUE 'LITER_PER_PASSENGER_KM';
ALTER TYPE "Unit" ADD VALUE 'LITER_PER_TON_KM';
ALTER TYPE "Unit" ADD VALUE 'MAX_TONNAGE';
ALTER TYPE "Unit" ADD VALUE 'PASSENGERS';
ALTER TYPE "Unit" ADD VALUE 'TON_GAZOLINE_PER_DAY';
ALTER TYPE "Unit" ADD VALUE 'TON_KM_PER_PERSON_YEAR';
ALTER TYPE "Unit" ADD VALUE 'KG_GAZOLINE_PER_TON_KM';
