-- CreateEnum
CREATE TYPE "Country" AS ENUM ('ALBANIA', 'ANDORRA', 'AUSTRIA', 'BELARUS', 'BELGIUM', 'BOSNIA_AND_HERZEGOVINA', 'BULGARIA', 'CROATIA', 'CYPRUS', 'CZECH_REPUBLIC', 'DENMARK', 'ESTONIA', 'FINLAND', 'FRANCE', 'GERMANY', 'GREECE', 'HUNGARY', 'ICELAND', 'IRELAND', 'ITALY', 'KOSOVO', 'LATVIA', 'LIECHTENSTEIN', 'LITHUANIA', 'LUXEMBOURG', 'MALTA', 'MOLDOVA', 'MONACO', 'MONTENEGRO', 'NETHERLANDS', 'NORTH_MACEDONIA', 'NORWAY', 'POLAND', 'PORTUGAL', 'ROMANIA', 'RUSSIA', 'SAN_MARINO', 'SERBIA', 'SLOVAKIA', 'SLOVENIA', 'SPAIN', 'SWEDEN', 'SWITZERLAND', 'UKRAINE', 'UNITED_KINGDOM', 'VATICAN_CITY', 'OTHER');

-- AlterTable
ALTER TABLE "sites" ADD COLUMN     "country" "Country";
